spring.profiles.active=dev
spring.application.name=meeting-map
server.port=8080
server.address=0.0.0.0

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#none: db\uB97C \uBCC0\uACBD\uD558\uC9C0 \uC54A\uC74C, create: \uC2E4\uD589\uB9C8\uB2E4 db \uC0C8\uB86D\uAC8C \uB9CC\uB4EC, update: \uC2E4\uD589\uB9C8\uB2E4 \uC2A4\uD0A4\uB9C8 \uC5C5\uB370\uC774\uD2B8, validate: \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC2A4\uD0A4\uB9C8\uAC00 \uC5D4\uD2F0\uD2F0\uC640 \uC77C\uCE58\uD558\uB294\uC9C0 \uD655\uC778
spring.jpa.hibernate.ddl-auto=validate

#JPA\uC5D0\uC11C mysql8\uC5B8\uC5B4\uB85C \uBCC0\uD658
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#JPA\uC5D0\uC11C SQL \uCFFC\uB9AC\uB97C \uCF58\uC194\uC5D0 \uCD9C\uB825
spring.jpa.show-sql=true

#jwt \uC554\uD638\uD654 \uD0A4(\uB79C\uB364 \uBB38\uC790\uC5F4 50\uC790)
spring.jwt.secret=REDACTED_JWT_SECRET

# \uCE74\uCE74\uC624 \uD0A4 \uC124\uC815  \uC218\uC815\uC644\uB8CC
kakao.api.base-url=https://dapi.kakao.com
kakao.api.admin-key=REDACTED_KAKAO_ADMIN
kakao.api.rest-api-key=REDACTED_KAKAO_REST

# TourAPI \uC124\uC815  \uC218\uC815\uC644\uB8CC
tour.api.base-url=http://apis.data.go.kr/B551011/KorService2
tour.api.key=REDACTED_TOUR_KEY

# \uAD6C\uAE00 API \uC124\uC815 (\uC6D0\uBCF8)
#google.api.base-url=https://maps.googleapis.com/maps/api
#google.api.key=REDACTED_GOOGLE_KEY_OLD

# \uAD6C\uAE00 API \uC124\uC815 (\uC784\uC2DC)
google.api.base-url=https://maps.googleapis.com/maps/api
google.api.key=REDACTED_GOOGLE_KEY


# TMap API \uC124\uC815  \uC218\uC815\uC644\uB8CC
tmap.api.base-url=https://apis.openapi.sk.com.
tmap.api.key=REDACTED_TMAP_KEY

# s3 API \uC124\uC815 (\uC6D0\uBCF8)
#cloud.aws.credentials.access-key=REDACTED_AWS_KEY_OLD
#cloud.aws.credentials.secret-key=REDACTED_AWS_SECRET_OLD
#cloud.aws.region.static=ap-northeast-2
#cloud.aws.s3.bucket=meeting-map-s3

# s3 API \uC124\uC815 (\uC784\uC2DC)
cloud.aws.credentials.access-key=REDACTED_AWS_KEY
cloud.aws.credentials.secret-key=REDACTED_AWS_SECRET
cloud.aws.region.static=aasddp-northeaasdasdst-234
cloud.aws.s3.bucket=meetidsng-masadasdp-s3dasa

# openai API \uC124\uC815  \uC218\uC815\uC644\uB8CC
openai.api.base-url=https://api.openai.com
openai.api.key=Bearer REDACTED_OPENAI_KEY

logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.org.springframework.web.reactive.function.client.RequestBodySpec=DEBUG
logging.level.org.springframework.web.reactive.function.client.ResponseBodySpec=DEBUG
logging.level.reactor.netty.http.client.HttpClient=DEBUG
logging.level.com.capstone.meetingmap.config.ExternalApiRestClientConfig=DEBUG

logging.file.path=logs
logging.file.name=logs/app.log