spring.profiles.active=dev
spring.application.name=meeting-map
server.port=8080
server.address=0.0.0.0

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# none: db를 변경하지 않음, create: 실행마다 db 새롭게 만듦, update: 실행마다 스키마 업데이트, validate: 데이터베이스 스키마가 엔티티와 일치하는지 확인
spring.jpa.hibernate.ddl-auto=validate

# JPA에서 mysql8언어로 변환
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA에서 SQL 쿼리를 콘솔에 출력
spring.jpa.show-sql=true

# JWT 암호화 키 (환경변수에서 읽어옴)
spring.jwt.secret=${JWT_SECRET}

# 카카오 API 설정
kakao.api.base-url=https://dapi.kakao.com
kakao.api.admin-key=${KAKAO_ADMIN_KEY}
kakao.api.rest-api-key=${KAKAO_REST_API_KEY}

# TourAPI 설정
tour.api.base-url=http://apis.data.go.kr/B551011/KorService2
tour.api.key=${TOUR_API_KEY}

# 구글 API 설정
google.api.base-url=https://maps.googleapis.com/maps/api
google.api.key=${GOOGLE_API_KEY}

# TMap API 설정
tmap.api.base-url=https://apis.openapi.sk.com
tmap.api.key=${TMAP_API_KEY}

# AWS S3 설정
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION:ap-northeast-2}
cloud.aws.s3.bucket=${AWS_S3_BUCKET}

# OpenAI API 설정
openai.api.base-url=https://api.openai.com
openai.api.key=${OPENAI_API_KEY}

# 로깅 설정
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
logging.level.org.springframework.web.reactive.function.client.RequestBodySpec=DEBUG
logging.level.org.springframework.web.reactive.function.client.ResponseBodySpec=DEBUG
logging.level.reactor.netty.http.client.HttpClient=DEBUG
logging.level.com.capstone.meetingmap.config.ExternalApiRestClientConfig=DEBUG

logging.file.path=logs
logging.file.name=logs/app.log
